### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-tree-frogs#1]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
* The logo will be top left upon page load. 
* The logo will print two sides: the light side, and dark mode.
* Input field will be centered on the top of the page, and broken up into two different sections:
            * Name
            * Comment
* Clear button will be off to the right of the input field. 
* (See comment below for more formatting)

**Comment by phillipsja97** [comment]
![image](https://user-images.githubusercontent.com/51938283/66882068-a0949f80-ef8e-11e9-98fb-0ca81c035d4e.png)
